name: eshop
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  marquee: ^2.2.0
  lottie: 1.2.2
  http: 0.13.4
  shared_preferences: 2.0.13
  connectivity: 3.0.6
  jaguar_jwt: 3.0.0
#  flutter_stripe:
  flutter_local_notifications: ^9.4.0
  path_provider: 2.0.9
  firebase_messaging:
  cached_network_image: 3.2.0
  flutter_rating_bar: 4.0.0
  flutter_html: 3.0.0-alpha.2
  photo_view: ^0.13.0
  flutter_webview_plugin: ^0.4.0
  firebase_auth:
  sms_autofill: 2.2.0
  intl: 0.17.0
  country_code_picker: 2.0.2
  google_maps_flutter: ^2.1.3
  geolocator: ^8.2.0
  file_picker: ^4.5.1
  shimmer: 2.0.0
  geocoding: ^2.0.4
#  razorpay_flutter: ^1.3.0
  curved_navigation_bar: 1.0.3
#  flutter_paystack: 1.0.5+1
  flutter_html_to_pdf: ^0.7.0
  permission_handler: ^9.2.0
  in_app_review: 2.0.4
  firebase_dynamic_links: ^4.0.7
  open_file: 3.2.1
  provider:
  video_player: ^2.2.13
  flutter_svg: ^1.0.3
  youtube_player_flutter: 8.0.0
  share: 2.0.4
  package_info: 2.0.2
  url_launcher: ^6.0.3
  version: ^2.0.0
  webview_flutter: ^3.0.2
  downloads_path_provider_28:
    path: ./downloads_path_provider

  libphonenumber: ^2.0.2
  firebase_core: ^1.13.1
  store_redirect: ^2.0.1
  paginate_firestore: 1.0.1
  firebase_storage:
  image_picker: ^0.8.0+3
  cloud_firestore: ^2.4.0
  flutter_linkify: ^5.0.2
  media_picker: ^1.3.5
  rxdart: ^0.27.1
  stacked: ^2.1.8
  get:
  flutter_screenutil: ^5.0.0+2


  rate_my_app: ^1.1.2
  rating_dialog: ^2.0.4
  flutter_share_me: ^1.3.0
  flutter_phone_direct_caller: ^2.1.1










dependency_overrides:
  firebase_core_platform_interface: 4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - lib/Language/
    - assets/animations/



  fonts:
    - family: opensans
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf